### ISSUE TITLE
Bedrock players not prompted to select origin on first join

### ISSUE THREAD

**Issue by Wolfcoool** [cometcake575/Origins-Reborn#4]
Hi, I'm running version 2.1.9 on 1.20.4 and when bedrock players join through geyser, they are not prompted to select their origin.
Giving a bedrock player an orb shows the selection does work, it is just not coming up on first join. 

Also, bedrock players are not sent the resource pack, is this intended? and does it break any functions besides the orb looking like a nautilus shell?

**Comment by cometcake575** [comment]
That's strange, it should be working fine - are there any errors in the console?

The resource pack not sending is intentional - it may be implemented in the future, but as Bedrock uses forms rather than the custom GUI it's only used for the orb of origin
