### ISSUE TITLE
OriginSwapper.java is causing memory leaks and crashing the server

### ISSUE THREAD

**Issue by Samuelblue123** [cometcake575/Origins-Reborn#9]
For some reason OriginSwapper.java is causing huge amounts of lag and causing the server to crash, i have no idea how to fix this on the server end.

**Comment by cometcake575** [comment]
Could you send your timings report?

**Comment by cometcake575** [comment]
Sorry, just realised I accidentally closed the issue - could you send your timings report?

**Comment by Samuelblue123** [comment]
where would i find that again?
also thanks for the speedy responses

**Comment by cometcake575** [comment]
It depends what you're using for information on timings - it's likely to be something like Spark

What was it that detected that OriginSwapper was causing a memory leak? I suggest just sending the report from that.
